### PR TITLE
closes #63

### LINKED ISSUE #63: The first parameter p in mat.options is wrong when cat.map is not NULL
This is wrong:
```
p = ifelse(is.null(cat.map), ncol(X), length(cat.map))
```

I believe this would be correct:
```
p = ifelse(is.null(cat.map), ncol(X), length(cat.map) + cat.map[[1L]][1L] - 1L)
```

Basically p is currently only counting categorical features but it needs to count numeric features, which it can get from the first element of cat.map

### PR DESCRIPTION
**Pull request by MrAE**
Updates to default sparsity and fixes for when categorical and continuous features are present.

### CODE REVIEW

File: R/RerF.R [hunk 1]
```diff
@@ -93,6 +96,35 @@ RerF <-
 		# na.action = function (...) { Y <<- Y[rowSums(is.na(X)) == 0];  X <<- X[rowSums(is.na(X)) == 0, ] },
 		# @param na.action action to take if NA values are found. By default it will omit rows with NA values. NOTE: na.action is performed in-place. See default function.
 
+    defaults <- function(paramList){
```
Comment (falkben) [inline R/RerF.R]: move to randmat file so it can be documented there

then it can be called with ?rerf:::defaults to see the defaults

Comment (MrAE) [reply R/RerF.R]: I found out that it can be called simply with `?defaults` after `rerf` is loaded.
